# Generated by Django 5.1 on 2024-09-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_products_items_remaining_alter_products_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='feature3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='feature4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='feature5',
        ),
    ]
